language: php
php:
  - '7.0'
services:
  - mysql
install:
  - sudo apt update -qq
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
  - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
  - sudo apt install -y apache2 libapache2-mod-fastcgi
  - pwd

script:
  - php -f ci/setup.php testing-framework
  - php -f ci/run.php master